name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest black

      - name: Lint code with black
        run: black --check app/ tests/

      - name: Run unit tests
        run: pytest tests/

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t churn-app .